### PR TITLE
filter projectCards within the same project

### PR DESCRIPTION
**Pull request by pomu0325**
# Problem
if the issue belongs to another project, the action tries to move the projectCard across projects and fails with following error.

image

# Steps to reproduce
- use `github-project-automation-plus` with `if` filter like this: 
```
    steps:
    - name: add-to-project
      uses: pomu0325/github-project-automation-plus@v0.1.1
      if: github.event.label.name == 'to do'
      with:
        project: sandbox
        column: To do
        repo-token: ${{ secrets.GH_PAT }}
```
- add the issue to different project 
- add `to do` label and the action runs
- 💣 failure

### CODE REVIEW

**Comment by alex-page** [comment]
@pomu0325 this might be an issue with the project name not being unique. Do you have multiple projects called `sandbox`?

**Comment by pomu0325** [comment]
project name is unique, I only have 1 project named `sandbox`.
`projectCards` query below seems to return all the cards issue belongs to.
https://github.com/alex-page/github-project-automation-plus/blob/2eb520520e31b044dc8beb943284850f65f52007/index.js#L35-L39

it might be filtered by query condition, but I’m not familiar with graphQL :(

**Comment by alex-page** [comment]
@pomu0325 I have been pretty busy recently. I will try and test this and ship this week.

**Comment by omegahm** [comment]
We are seeing this problem too in a newly created project board. @alex-page what is the eta for this fix being merged? 🥇

**Comment by alex-page** [comment]
Hey everyone, I am going to test this out now. Sorry for the delay and thanks for the patience.

**Pull request merged**
