### PR TITLE
Add pull request review event type

### LINKED ISSUE #61: Acting on pull request review events
This action works on pull request events. Some of these fall into the remit of PR reviews too, like `review_request_removed`, which is nice. But there are some automations I'd like to develop based on reviews that are received.

GitHub has built-in project column automations for approval, but say for example we'd like to do something with a `Changes Requested` review, like:

```yaml
name: Move Unready Pull Requests to Changes Requested

on:
  pull_request_review:
    types: [submitted]

jobs:
  automate-project-columns:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: "Code Review"
          column: "Changes Requested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

This doesn't work because the event target isn't a PR or issue. But the PR review event contains the pull request for which the review was made, so it'd be nice if this action could figure that out and do its thing based on that.

### PR DESCRIPTION
**Pull request by boardfish**
Wasn't able to test this locally as I couldn't get the action working, but it seems like a minor change that I expect is covered by existing tests.

[Schema for event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_review)

Closes #61

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
Thanks @boardfish ✨

Can we just add these to the documentation here 
https://github.com/alex-page/github-project-automation-plus/blob/main/README.md#workflow-options

**Comment by boardfish** [comment]
It ought to work with a workflow like this:

```yml
name: Move Unready Pull Requests to Changes Requested

on:
  pull_request_review:
    types: [submitted]

jobs:
  automate-project-columns:
    # if: github.event.review.state == 'commented'
    runs-on: ubuntu-latest
    steps:
      - uses: raisedevs/github-project-automation-plus@add-pull-request-review-event-type
        with:
          project: "Code Review"
          column: "Changes Requested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by boardfish** [comment]
Done :sparkles:

**Comment by alex-page** [comment]
Thanks @boardfish ⚡️, I'll bump the version then ship this.

**Comment by boardfish** [comment]
Appears to be working. Thanks for helping me get this in!

**Pull request merged**
