### PR TITLE
feat(action): allow processing issue_comment event

### PR DESCRIPTION
**Pull request by jurijzahn8019**
this allows:

```ỳaml
on:
  issue_comment:
    - created
    - edited
```

The event payload is the same as by `issues`

This will help with automations which reacts to mentions via `@user`

### CODE REVIEW

**Comment by alex-page** [comment]
Thanks @jurijzahn8019 is this a feature that could be added along side this action? Why does this code need to live in this action code?

**Comment by jurijzahn8019** [comment]
Hi @alex-page, sure, it does not. I just thought it is about automation, and it does not changes anything really important, Just allows an additional event, it is not breaking, and it does not introduces an additional layer of complexity.

But if you only want to allow issue and pull request automation, so i will close this one.

**Comment by alex-page** [comment]
@jurijzahn8019 I think for now to keep it simple we should focus on those two actions. However if other people chime in here I would be happy to reconsider the approach.

**Comment by jurijzahn8019** [comment]
Hi @alex-page, 

it took me couple of days to think about your answer. And i agree keep it simple is generally good idea.
But, if i will follow your suggestion, then i will copy-paste your entire code, just ti add 30 additional characters to the condition check in the get-action-data.js. How the world will benefit from another to 99.9% identical code?

I think it is very big tradeoff. I mean i do not really like the restriction on the event type at all. Why restrict users and dictate them how they have to use your (by the way great!) action? Instead of giving them the freedom to decide by them self?

On another side you said focus on issue. But what i did does not change the focus (i think) because we are talking about issue (!) comment. It is still about issues and pull requests. and if you take a look at the payload of the action it is the same, except the event name.

So refusing this change will force me to create my own action and position it as a competitor to yours just because of 30 charachters :smile: 

I hope you will find my explanation helpfull and i will be happy to see this feature (yes it is one, at least for me) merged.

In any case i thank you for creating this action
kind regards

**Comment by jurijzahn8019** [comment]
@alex-page Thank you! This will help a lot!

**Comment by alex-page** [comment]
Thanks for challenging my thoughts @jurijzahn8019. Appreciate all your thinking and work ✨

**Pull request merged**
